architecture: standalone
auth:
  enabled: true
  existingSecret: 'redis-credentials'
  existingSecretPasswordKey: REDIS_PASSWORD
master:
  resources:
    requests:
      cpu: 125m
      memory: 128Mi
    limits:
      memory: 256Mi
