apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: backstage
stringData:
  POSTGRESQL_USERNAME: {{ REDIS_USERNAME }}
  POSTGRESQL_PASSWORD: {{ REDIS_PASSWORD }}
  POSTGRESQL_HOST: backstage-postgresql
  POSTGRESQL_PORT: "{{ REDIS_PORT }}"
